### ISSUE TITLE
Error while deploying Logic App Standard via Visual studio Code

### ISSUE THREAD

**Issue by hluhana-equinor** [Azure/logicapps#665] opened 2022-11-01 09:24 UTC
### Describe the Bug

Error while deploying Logic app standard 

![image](https://user-images.githubusercontent.com/91068328/199201763-8853f9aa-5704-4db7-aa90-2a3376bd0503.png)

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

1. Right Click on Stateful process
2. Deploy to Logic App

AB#16096279

**Comment by hartra344** [comment] 2022-11-01 17:20
Closing as a duplicate of #666, @ccastrotrejo  is already looking into this :)

**Closed by hartra344** 2022-11-01 17:20 UTC
