### ISSUE TITLE
Connectors gives error: "Could not retrieve values. getConfiguration is not a function"

### ISSUE THREAD

**Issue by yoHasse** [Azure/logicapps#609] opened 2022-08-31 12:03 UTC
While adding triggers or action like Service Bus/Invoke Workflow/Function App etc. (all of them result in the same error) I constantly get the following error:   
"Could not retrieve values. getConfiguration is not a function"

Tried with different computers and colleagues also have the same issue.

We have to enter the value manually however it's confusing at first because you beleive there's something wrong with the setup.

![image](https://user-images.githubusercontent.com/20658270/187662222-054878b0-963d-4f15-aa1c-98f9ebd28b09.png)

AB#15956306

**Comment by John-Bosch** [comment] 2022-09-01 04:55
This appears to be happening on a number of connectors at the moment within VS Code and looks to be due to something changed in the 1.0.34 version of the VS Code extension. Rolling the Logic App (Standard) extension back to 1.0.25 fixed the issue for us.

We spotted it first on the "Call another workflow" connector.

**Comment by yoHasse** [comment] 2022-09-01 05:53
> This appears to be happening on a number of connectors at the moment within VS Code and looks to be due to something changed in the 1.0.34 version of the VS Code extension. Rolling the Logic App (Standard) extension back to 1.0.25 fixed the issue for us.
> 
> We spotted it first on the "Call another workflow" connector.

Thank you! Noticed the same problem with other connectors and the rollback to 1.0.25 solved it for us too.
Updating title to involve all connectors.

**Comment by MayankBargali-MSFT** [comment] 2022-09-09 05:02
@ccastrotrejo Can you please review this? I couldn't reproduce the issue at my end but multiple customers are reporting the same issue https://docs.microsoft.com/en-us/answers/questions/989766/logic-app-standard-extension-v1034-has-broken-some.html

**Comment by ccastrotrejo** [comment] 2022-09-09 14:14
@MayankBargali-MSFT thank you very much for tagging me. I acknowledge this, I have created a task to solve this issue.

**Comment by enhendrickson** [comment] 2022-09-23 21:42
I'm seeing this as well

**Comment by ccastrotrejo** [comment] 2022-11-08 18:11
Hi all, this issue is happening because a feature is not implemented yet in designer. There is an inner task to work on it, once that task is completed, I will verify this bug fix.

**Comment by ccastrotrejo** [comment] 2022-11-08 23:32
Issue should be fixed for next extension version

**Closed by ccastrotrejo** 2022-11-08 23:32 UTC
Labels: bug, enhancement, vscode
