### ISSUE TITLE
nextPageLink cannot be null or undefined.

### ISSUE THREAD

**Issue by pruva4** [Azure/logicapps#477] opened 2022-02-17 04:26 UTC
Does this occur consistently? 
Repro steps:

1. I logged in to VScode and connected my Azure subscription and opened the logic app, clicking load more as per below screenshot and faced the issue as per the log 
![image](https://user-images.githubusercontent.com/98962557/154405303-8d77355a-362a-492d-87ca-6ef98498d994.png)

Action: azureLogicAppsStandard.loadMore
Error type: Error
Error Message: nextPageLink cannot be null or undefined.

Version: 1.0.12
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.64.2
Language: en

<details>
<summary>Call Stack</summary>

```
Serializer.serialize extension.bundle.js:2:1745632
getOperationArgumentValueFromParameterPath extension.bundle.js:2:1766280
getOperationArgumentValueFromParameter extension.bundle.js:2:1765787
WebSiteManagementClient.ServiceClient.sendOperationRequest extension.bundle.js:2:1762226
WebApps.listNext extension.bundle.js:2:553028
SubscriptionTreeItem.<anonymous> extension.bundle.js:2:4643011
fulfilled extension.bundle.js:2:4642033
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by joechung-msft** [comment] 2022-02-17 05:44
Duplicate of #332

**Closed by joechung-msft** 2022-02-17 05:44 UTC
