### ISSUE TITLE
Error when clicking Load More

### ISSUE THREAD

**Issue by inaun** [Azure/logicapps#325] opened 2021-07-08 19:50 UTC
Does this occur consistently? Yes
Repro steps:
Click "Load More..." in Visual Studio Code Logic Apps (standard) under a logic app

1.
2.

Action: azureLogicAppsStandard.loadMore
Error type: Error
Error Message: nextPageLink cannot be null or undefined.

Version: 1.0.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.57.1
Language: en

<details>
<summary>Call Stack</summary>

```
Serializer.serialize extension.bundle.js:2:1745717
getOperationArgumentValueFromParameterPath extension.bundle.js:2:1766365
getOperationArgumentValueFromParameter extension.bundle.js:2:1765872
WebSiteManagementClient.ServiceClient.sendOperationRequest extension.bundle.js:2:1762311
WebApps.listNext extension.bundle.js:2:553051
SubscriptionTreeItem.<anonymous> extension.bundle.js:2:4633675
fulfilled extension.bundle.js:2:4632717
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by zhangadreedom** [comment] 2021-08-20 08:04
Hello @inaun can you provide the screenshot of this error? in which step you click 'Load More' shows this error?

**Comment by joechung-msft** [comment] 2022-02-17 05:43
Duplicate of #332

**Closed by joechung-msft** 2022-02-17 05:43 UTC
