### ISSUE TITLE
Actions with managed connectors described as app settings parameters are not properly visible in LA Standard Designer 

### ISSUE THREAD

**Issue by WenovateAA** [Azure/logicapps#463] opened 2022-02-01 13:35 UTC
Hi,

Since yesterday I see error in designer for actions using managed connectors: `The provided subscription identifier '@appsetting('WORKFLOWS_SUBSCRIPTION_ID')' is malformed or invalid.` 
![image](https://user-images.githubusercontent.com/97520510/151975969-78e2833b-ebfd-45fa-9ae6-bf36d78e0350.png)
Connectors are configured using app setting parameters: 

````json
"azuretables": {
            "api": {
                "id": "/subscriptions/@appsetting('WORKFLOWS_SUBSCRIPTION_ID')/providers/Microsoft.Web/locations/westeurope/managedApis/azuretables"
            },
            "authentication": {
                "type": "ManagedServiceIdentity"
            },
            "connection": {
                "id": "/subscriptions/@appsetting('WORKFLOWS_SUBSCRIPTION_ID')/resourceGroups/@appsetting('WORKFLOWS_RESOURCE_GROUP_NAME')/providers/Microsoft.Web/connections/azuretables"
            },
            "connectionRuntimeUrl": "@appsetting('AZURETABLES_CONNECTION_RUNTIMEURL')"
        }
````
Similar problem can be seen in workflow's run history: ![image](https://user-images.githubusercontent.com/97520510/151975820-1939a420-11b6-43a4-9a18-39e2c800d2e6.png)

This is a way described in CI/CD example of LA dev sample: https://github.com/Azure/logicapps/tree/master/azure-devops-sample 
It doesn't prevent a workflow from running, somehow designer can't treat it properly. Problem was first detected yesterday, after some time dissapeared, now I see it again. Connector configuration is active since several months and problem are observed only now.

**Comment by rob-thijssen** [comment] 2022-02-01 15:48
Exact same behaviour on my side!
Please provide the fix asap. It took me all day up-to-now to find out if the error was somehow invoked by me with a wrong deployment or so. Thanks to this post I found out that the logicapp run will not (yet) be influenced.
I even tried to add { } to the appsetting as the new documentation ([here](https://docs.microsoft.com/en-us/azure/logic-apps/parameterize-workflow-app?tabs=azure-portal#parameterize-connections-file)). No difference. Error still visible in designer.
As an addition to this issue:
The connections overview also displays errors:
![image](https://user-images.githubusercontent.com/98831650/152001068-4f694fb1-2496-4b71-9e4c-abb8e71019d7.png)
and
![image](https://user-images.githubusercontent.com/98831650/152001293-1d71a7c8-d0e0-4fac-b617-38b134667e68.png)
with { }:
![image](https://user-images.githubusercontent.com/98831650/152001552-0b22cd4d-8d32-445c-b9f7-4b455702f776.png)

**Comment by motterasysco** [comment] 2022-02-02 11:49
Same issue with me as well. I discovered this today.

**Comment by hartra344** [comment] 2022-02-02 18:50
We have figured out the cause and have started to deploy a fix. Due to how our deployments happen as a rollout this may take a few days to fully reach production. 

In the meantime here is a link that will make sure the fixed bits load if this is something that is blocking your workflow: https://aka.ms/logicAppActionFix

**Comment by motterasysco** [comment] 2022-02-04 13:26
Still the same issue (northeurope). Can you explan the fix you provides here? Does not do much..

> We have figured out the cause and have started to deploy a fix. Due to how our deployments happen as a rollout this may take a few days to fully reach production.
> 
> In the meantime here is a link that will make sure the fixed bits load if this is something that is blocking your workflow: https://aka.ms/logicAppActionFix

**Comment by rob-thijssen** [comment] 2022-02-23 07:48
Follow-up:
I have been monitoring our logicapps last week and this issue seems to be fixed in West Europe.

**Comment by rob-thijssen** [comment] 2022-03-15 10:50
Same problem is also happening again to here @hartra344 .
Region: West Europe

**Comment by krisvijaykb** [comment] 2022-03-16 13:39
Same issue. Any updates on this?

**Comment by krisvijaykb** [comment] 2022-03-19 07:06
The issue got resolved automatically for me.

**Comment by bizintelligence** [comment] 2022-03-30 00:31
Hi, 
I have been facing the same issue. However, I have noted that if I use curly bracket in local development environment then it works locally but once it is deployed to Logic App then I see "malformed" message.

Therefore, I tried to remove the curly bracket before publishing it to remote repo. It works on Logic App. 

**Before**
{
  "managedApiConnections": {
    "office365": {
      "api": {
        "id": "/subscriptions/@{appsetting('WORKFLOWS_SUBSCRIPTION_ID')}/providers/Microsoft.Web/locations/australiasoutheast/managedApis/office365"
      },
      "connection": {
        "id": "/subscriptions/@{appsetting('WORKFLOWS_SUBSCRIPTION_ID')}/resourceGroups/@{appsetting('WORKFLOWS_RESOURCE_GROUP_NAME')}/providers/Microsoft.Web/connections/office365"
      },
      "connectionRuntimeUrl": "@{appsetting('OFFICE365_CONNECTION_RUNTIMEURL')}",
      "authentication": {
        "type": "ManagedServiceIdentity"
      }
    }
  }
}
**After**
{
  "managedApiConnections": {
    "office365": {
      "api": {
        "id": "/subscriptions/@appsetting('WORKFLOWS_SUBSCRIPTION_ID')/providers/Microsoft.Web/locations/australiasoutheast/managedApis/office365"
      },
      "connection": {
        "id": "/subscriptions/@appsetting('WORKFLOWS_SUBSCRIPTION_ID')/resourceGroups/@appsetting('WORKFLOWS_RESOURCE_GROUP_NAME')/providers/Microsoft.Web/connections/office365"
      },
      "connectionRuntimeUrl": "@appsetting('OFFICE365_CONNECTION_RUNTIMEURL')",
      "authentication": {
        "type": "ManagedServiceIdentity"
      }
    }
  }
}

> However, this is so much pain. There has to be fix for it.

**Comment by AbodeSaafan** [comment] 2022-03-30 23:02
Hello,

There was a bug that we hotfixed that solved the issue mentioned earlier in this thread. 

@bizintelligence We are aware of this issue. Basically, right now, if you are developing with the designer on the portal, you must use the appsetting/parameter expression in connections.json without the proper string interpolation format, so, without the wrapping { }. 

We are working on a plan to bring the support to use the proper string interpolated format to the portal designer. When we have that, we will share it with you and other customers and clearly outline what is supported. 

Let me know if you have any other questions here.

**Closed** 2022-03-30 23:02 UTC
Labels: bug

**Comment by nikhilbattula9** [comment] 2022-12-28 17:13
My logic app is in switzerland north region .I got the same error tried using both ways without using curly braces @appsetting('subscription_id') and with curly braces @{appsetting('subscription_id')} . app setting parameter values is'nt reflecting into the connections.json file. Could u guys pls let me know if you found any work around (except creating mutliple files for each environment)
