### ISSUE TITLE
'Run Trigger' button in Azure Portal always disabled for HTTP triggered workflows

### ISSUE THREAD

**Issue by John-Bosch** [Azure/logicapps#573] opened 2022-06-19 22:26 UTC
The 'Run Trigger' button is always blank on every one of my HTTP triggered workflows. 

![image](https://user-images.githubusercontent.com/5135377/174502542-4e85e0cb-fd0e-478b-a4f7-92a2ad78f81f.png)

The button is enabled briefly while the Javascript loads, but as soon as the Workflow URL and other bits and pieces populate it is disabled.

If it helps, all of my logic apps are developed in VS Code and deployed via Azure Dev Ops.

AB#15957211

**Comment by TWolverson** [comment] 2022-07-14 17:22
I'm also encountering this, except that it's not **always** greyed out. I once managed to snatch it quickly enough to create a run, thereafter it was greyed out.

The browser console sometimes logs a spurious error message relating to listing the LA's triggers, which I can't reproduce now. I notice that the Run Trigger button flashes enabled before the page is fully loaded, and greys out too fast to navigate to it.

Restarting the Logic App seems to sometimes bring it back, but it quickly disables again afterwards.

**Comment by John-Bosch** [comment] 2022-10-20 21:45
Thanks Git-Bot. All you have to do is ignore an issue long enough and it goes away!

**Comment by hartra344** [comment] 2022-10-22 03:14
Sorry, I'm slowly trying to get a handle on these issues and the github bot is helping me surface which issues are still issues. Thanks for responding 😄 

As far as the issue, it looks like for this field we're conflating a permission check with a read only check of the app. Since you're using zip deploy as part of the ADO deployment, your workflow is in a read only state. I'm making a commit now to fix this. Should be in production in a couple weeks as part of the normal deployment process.

**Comment by John-Bosch** [comment] 2022-10-22 07:19
Thank you for the update @hartra344. Thanks again for getting the fix in promptly.

**Comment by hartra344** [comment] 2022-10-30 22:09
The fix for this has gone through testing and will be rolling out starting next week. Feel free to reopen if it's not fixed by Oct 8th

**Closed by hartra344** 2022-10-30 22:09 UTC
Labels: bug, UX
