### ISSUE TITLE
Standard_Manage Identity_Showing error.

### ISSUE THREAD

**Issue by v-prakumar** [Azure/logicapps#840] opened 2023-07-25 12:43 UTC
### Describe the Bug

Disabling the system assigned manage identity after successful run, the designer is enabled to load.

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

1.Create a Standard Logic app in Brazil South location and add stateful workflow.
2. Enable the system assigned manage identity if it is disable save it from Identity tab.
3. Open Designer and add http trigger.
4. Select create job from Azure Automation with MI action and create the connection with manage identity.
5. Fill all the needed details: For it Add role assignment and give contributor access to your Logic app Subscription, Resource group and automation account. For this refer the test case scripts i.e., T1.27 Manage identity connection in standard.
6.Save it after step5 and run the workflow.
7.After successful run, Disable the manage identity, go back to designer and try to open the workflow.

**Expected:** As identity is disabled, Workflow should be showing error related to disable identity.

**Actual:** Error while loading the page.
![image](https://github.com/Azure/logicapps/assets/92098490/eb1b4420-378f-49e5-a6c5-75cdbd427514)

### Additional context

Environmental Details:

URL: [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-prakumar%40microsoft.com%7Ca4c5f9ea325944add5ef08db8c62845c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638258127124642155%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Zs2FX35VmN5yKZw4GXmgt0%2B5u3%2Fz1oQtaedvKK3Mvp8%3D&reserved=0)

Version: 2.30717.1.3

AB#24638415

**Comment by rllyy97** [comment] 2023-07-25 16:33
I've investigated this issue and am able to reproduce, but it only happen on the first load.
When I experience the error I just have to reload and it loads fine with the proper error message.

**Comment by vgouth** [comment] 2023-08-08 04:36
Issue repro in the latest request.

Agreed with @rllyy97. But when we reload the logic app for the second time, we are able to see the error related to disable identity but after 30 seconds getting the below error page. Page is not stable.

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C25ee41df62d44438790c08db937727d7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638265912263218130%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ExdI18ub8D3V7ulDw4BDJPTB28t6zLoS8UczXvO%2FLFw%3D&reserved=0)
**Version:** 2.30731.1.4

![image](https://github.com/Azure/logicapps/assets/113517384/f5d230ab-0ba4-425d-8fed-6e9746d67e51)

**Comment by vgouth** [comment] 2023-08-15 17:22
Issue repro in the latest request

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C08587520e7324008a23608db9d720c7f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638276885447380759%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=etlI5s6BaGn77nqLx5H9zxtbj797x8RnC1ZNmMz8rjQ%3D&reserved=0)
**Version:** 2.30814.1.1

![image](https://github.com/Azure/logicapps/assets/113517384/401a9af5-0a72-4987-9d70-953973898ec4)

**Comment by vgouth** [comment] 2023-08-30 13:50
Issue repro in the latest request.

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C18a8b542b1764bd310b408dba93133ed%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638289801129729358%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Wver%2BsKkXAoPcJFkMT%2FOj9%2FZg9i4gj8Sa%2FF8mmTQgTA%3D&reserved=0)
**Version:** 2.30828.1.2

![image](https://github.com/Azure/logicapps/assets/113517384/6da5c5fd-dd59-46e1-9476-d5e8b8ec8b12)

**Comment by vgouth** [comment] 2023-10-12 11:07
Issue repro in the latest request. Attaching the HAR file for the same

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C812ecec939f943a0236b08dbcadb1346%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638326814546516488%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oaldsNa7sJEgX1lgFphSQLXmtCRZ%2FUm2tHxNj1Vff2I%3D&reserved=0)
**Version:** 2.31010.1.2

[managedidentity.zip](https://github.com/Azure/logicapps/files/12880708/managedidentity.zip)
![image](https://github.com/Azure/logicapps/assets/113517384/e7219c60-c8a2-46bb-bf94-6ef0bfa5ec34)

**Comment by rllyy97** [comment] 2023-10-12 16:54
@vgouth was this ever fixed / is this a regression, or has this still been occurring since you last commented in August?

**Comment by vgouth** [comment] 2023-10-13 04:04
@rllyy97 . It has still been occurring. In the month of September, I am not able to test this particular test case due to screen drop down issue where I cannot find create connection option, which has been fixed now.

**Comment by vgouth** [comment] 2023-11-10 14:17
Issue repro in the latest request 

**Environmental Details:
Version:** 2.31108.1.1
![image](https://github.com/Azure/logicapps/assets/113517384/eb8ac8c8-50d8-493a-80cf-912131127156)

**Comment by Eric-B-Wu** [comment] 2024-07-11 21:09
closing this issue as it seems fixed now

**Closed by Eric-B-Wu** 2024-07-11 21:09 UTC
Labels: bug
