### ISSUE TITLE
nextPageLink cannot be null or undefined.

### ISSUE THREAD

**Issue by hargoivnd** [Azure/logicapps#557] opened 2022-06-02 03:16 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureLogicAppsStandard.loadMore
Error type: Error
Error Message: nextPageLink cannot be null or undefined.

Version: 1.0.19
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.67.2
Language: en

<details>
<summary>Call Stack</summary>

```
Serializer.serialize extension.bundle.js:2:1745635
getOperationArgumentValueFromParameterPath extension.bundle.js:2:1766283
getOperationArgumentValueFromParameter extension.bundle.js:2:1765790
WebSiteManagementClient.ServiceClient.sendOperationRequest extension.bundle.js:2:1762229
WebApps.listNext extension.bundle.js:2:553029
SubscriptionTreeItem.<anonymous> extension.bundle.js:2:4232283
fulfilled extension.bundle.js:2:4231305
```

</details>

**Comment by joechung-msft** [comment] 2022-06-09 13:02
Duplicate of #493

**Closed by joechung-msft** 2022-06-09 13:02 UTC
