### ISSUE TITLE
Local function within workflow

### ISSUE THREAD

**Issue by shankarmaha** [Azure/logicapps#177] opened 2020-09-28 11:06 UTC
In the private preview, you offered a action to call a local function (WorkflowActionTrigger) created within the workflow. However, I don't seem them within the public preview. Could you please let us know if you have plans to bring them into the public preview?

![image](https://user-images.githubusercontent.com/4720931/94424769-ad4fda80-0182-11eb-848d-8c2ed5d9432e.png)

![image](https://user-images.githubusercontent.com/4720931/94424885-dcfee280-0182-11eb-8bb0-032d41165603.png)

**Comment by derek1ee** [comment] 2020-09-28 16:33
Hi @shankarmaha, this area (code integration in workflow) is something we're actively looking into, experimenting, and changing, so expect features to change between private/public preview, and throughout public preview. 

What you see is an intentional change as we iterate on the experience, so I'm closing this issue as it's not a bug. We would, however, appreciate your feedback. You can submit them at aka.ms/lafeedback, and we'd appreciate if you can include reasons/scenarios why you find this option useful/want it back.

Thanks,
Derek

**Closed by derek1ee** 2020-09-28 16:33 UTC
