### ISSUE TITLE
404 UNidentified error while opening designer of workflow logic app standard thru VS Code

### ISSUE THREAD

**Issue by svinjimoorrtiorg** [Azure/logicapps#657] opened 2022-10-21 11:34 UTC
### Describe the Bug

I am trying open the Designer of logic apps standard workflow thru VS Code. while i try to do that i am getting below error in the output window  
[2022-10-21T11:09:18.276Z] Error fetching version information for extension bundle Microsoft.Azure.Functions.ExtensionBundle.Workflows
[2022-10-21T11:09:18.284Z] Unable to find or download extension bundle
[2022-10-21T11:09:18.966Z] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
For detailed output, run func with --verbose flag.
[2022-10-21T11:09:23.923Z] Host lock lease acquired by instance ID '0000000000000000000000005D11702C'.
4:41:58 PM: Running command: "func host start --port 8002"...
Port 8002 is unavailable. Close the process using that port, or specify another port using --port [-p].
4:45:36 PM: Error: 404 - undefined
4:47:42 PM: Error: 404 - undefined
4:48:42 PM: Running command: "func host start --port 8002"...
Port 8002 is unavailable. Close the process using that port, or specify another port using --port [-p].
4:55:52 PM: Error: 404 - undefined 

Please help me to understand and provide a fix for the above error

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

Go to Workflow.json 
Open the Workflow.json file
Right Click on Workflow.json file ---> Select Open in Designer

Getting above mentioned error.

AB#15945165

**Comment by hartra344** [comment] 2022-10-21 16:06
Closing as a duplicate of #655 . This should be resolved now.

**Closed by hartra344** 2022-10-21 16:06 UTC
