### ISSUE TITLE
Load More in Logic Apps (Standard) Panel of VS Code Generates Error

### ISSUE THREAD

**Issue by martinpeck** [Azure/logicapps#357] opened 2021-08-18 14:12 UTC
Does this occur consistently? Yes
Repro steps:

1. Sign into Azure within VS Code
2. Observe the Azure subscription name in "Logic Apps (Standard) panel)
3. Click "Load more..."

Action: azureLogicAppsStandard.loadMore
Error type: Error
Error Message: nextPageLink cannot be null or undefined.

Version: 1.0.3
OS: linux
OS Release: 5.10.25-linuxkit
Product: Visual Studio Code
Product Version: 1.59.0
Language: en

<details>
<summary>Call Stack</summary>

```
Serializer.serialize extension.bundle.js:2:1745717
getOperationArgumentValueFromParameterPath extension.bundle.js:2:1766365
getOperationArgumentValueFromParameter extension.bundle.js:2:1765872
WebSiteManagementClient.ServiceClient.sendOperationRequest extension.bundle.js:2:1762311
WebApps.listNext extension.bundle.js:2:553051
SubscriptionTreeItem.<anonymous> extension.bundle.js:2:4640610
fulfilled extension.bundle.js:2:4639652
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by zhangadreedom** [comment] 2022-01-27 05:38
Hi @martinpeck , can you uninstall VS extension and re-install again? if we have more Logic app, it will return a valid link back

**Comment by joechung-msft** [comment] 2022-02-17 05:43
Duplicate of #332

**Closed by joechung-msft** 2022-02-17 05:43 UTC
