### ISSUE TITLE
Use Azurite instead of Azure Storage Emulator

### ISSUE THREAD

**Issue by EldertGrootenboer** [Azure/logicapps#115] opened 2020-06-09 08:32 UTC
Everything points to Azurite becoming the new standard for local storage.

**Comment by tomkerkhove** [comment] 2020-06-09 09:09
Relates to #96

**Comment by MattFarm** [comment] 2020-06-09 16:57
Thanks Eldert, at the moment, Azurite is missing some key APIs that we need. We're working out what the best strategy is moving forward. Tagging @laveeshb and @rohithah for info.

**Comment by laveeshb** [comment] 2020-06-09 17:37
+1 to @MattFarm 
We want to use Azurite as well; however, it does not have all the APIs we need at this time.

**Comment by laveeshb** [comment] 2020-06-09 17:37
Resolving this as by design.

**Closed by laveeshb** 2020-06-09 17:37 UTC
Labels: preview
