### ISSUE TITLE
Error when attempting to use Azure Logic Apps (Standard) Extension

### ISSUE THREAD

**Issue by GravlLift** [Azure/logicapps#408] opened 2021-10-22 15:52 UTC
Does this occur consistently? Yes
Repro steps:

1. Click "Load More" in the VS Code Azure Logic Apps Sidebar.

Action: azureLogicAppsStandard.loadMore
Error type: Error
Error Message: nextPageLink cannot be null or undefined.

Version: 1.0.7
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.61.2
Language: en

<details>
<summary>Call Stack</summary>

```
Serializer.serialize extension.bundle.js:2:1745717
getOperationArgumentValueFromParameterPath extension.bundle.js:2:1766365
getOperationArgumentValueFromParameter extension.bundle.js:2:1765872
WebSiteManagementClient.ServiceClient.sendOperationRequest extension.bundle.js:2:1762311
WebApps.listNext extension.bundle.js:2:553051
SubscriptionTreeItem.<anonymous> extension.bundle.js:2:4640327
fulfilled extension.bundle.js:2:4639369
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by zhangadreedom** [comment] 2021-10-31 00:27
@GravlLift Thanks for your effort on this. Based on the screenshot provided, I think the issue may cause by there is no logic app standard under this subscription. It will load all logic app under subscription to display. I can't repro this issue due to it loads correctly, even the subscription I have no permission, it will show nothing instead of 'Load more'.....
By the way, we can use Azure Portal for better experience unless you want to debug logic app in local.

**Comment by puspraj-repos** [comment] 2021-12-08 09:29
@GravlLift , can you confirm if you are facing the issue even if you have logic app standard present in your subscription?

**Comment by joechung-msft** [comment] 2022-02-17 05:43
Duplicate of #332

**Closed by joechung-msft** 2022-02-17 05:43 UTC
