### ISSUE TITLE
issue when open a logic in vscode

### ISSUE THREAD

**Issue by edelahaie** [Azure/logicapps#493] opened 2022-03-10 09:26 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureLogicAppsStandard.loadMore
Error type: Error
Error Message: nextPageLink cannot be null or undefined.

Version: 1.0.12
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.65.1
Language: fr

<details>
<summary>Call Stack</summary>

```
Serializer.serialize extension.bundle.js:2:1745632
getOperationArgumentValueFromParameterPath extension.bundle.js:2:1766280
getOperationArgumentValueFromParameter extension.bundle.js:2:1765787
WebSiteManagementClient.ServiceClient.sendOperationRequest extension.bundle.js:2:1762226
WebApps.listNext extension.bundle.js:2:553028
SubscriptionTreeItem.<anonymous> extension.bundle.js:2:4643011
fulfilled extension.bundle.js:2:4642033
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by joechung-msft** [comment] 2022-06-09 16:32
Duplicate of #332

**Closed by joechung-msft** 2022-06-09 16:32 UTC
