### ISSUE TITLE
Error while loading Logic Apps Standard in Visual Studio Code Logic App Standard Extension

### ISSUE THREAD

**Issue by msitsoftware** [Azure/logicapps#432] opened 2021-11-26 10:03 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureLogicAppsStandard.loadMore
Error type: Error
Error Message: nextPageLink cannot be null or undefined.

Version: 1.0.8
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.62.3
Language: en

<details>
<summary>Call Stack</summary>

```
Serializer.serialize extension.bundle.js:2:1745717
getOperationArgumentValueFromParameterPath extension.bundle.js:2:1766365
getOperationArgumentValueFromParameter extension.bundle.js:2:1765872
WebSiteManagementClient.ServiceClient.sendOperationRequest extension.bundle.js:2:1762311
WebApps.listNext extension.bundle.js:2:553051
SubscriptionTreeItem.<anonymous> extension.bundle.js:2:4651058
fulfilled extension.bundle.js:2:4650080
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by ShreeDivyaMV** [comment] 2021-12-01 08:08
@msitsoftware , could you share the screenshot of the issue. If it is specific to loading any project, Could you share the project folder and we can try to load it at our end?

**Comment by msitsoftware** [comment] 2021-12-01 08:50
Sure. I also tested it right now on Mac OS with same result. So it is not specific to a project. I getting this error for all projects on any platform (Windows and Mac OS). I click on load more and the only thing I can see is the error notification.

![image](https://user-images.githubusercontent.com/69357066/144201767-e8bfc31d-5931-4594-9862-3b15fe8e116d.png)

**Comment by ShreeDivyaMV** [comment] 2021-12-07 15:01
@msitsoftware, thanks for the details. This would ideally load all the logic app resources available in your subscription instead of showing "Load More" option, as below.
![image](https://user-images.githubusercontent.com/30790938/145053225-4f7575ab-c7b0-49a2-9468-38d3dc1dcaf1.png)

Could you confirm if you have any logic app standard resources in your subscription. If not, could you add one from portal and try if you see the same issue?
And also are you able to load the resources for other extensions shown in the screenshot you provided- like Virtual machines or storage?

**Comment by joechung-msft** [comment] 2022-02-17 05:44
Duplicate of #332

**Closed by joechung-msft** 2022-02-17 05:44 UTC
