### ISSUE TITLE
Error: nextPageLink cannot be null or undefined.

### ISSUE THREAD

**Issue by Ramprasadaddanki** [Azure/logicapps#448] opened 2022-01-04 14:04 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureLogicAppsStandard.loadMore
Error type: Error
Error Message: nextPageLink cannot be null or undefined.

Version: 1.0.10
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.63.2
Language: en

<details>
<summary>Call Stack</summary>

```
Serializer.serialize extension.bundle.js:2:1745717
getOperationArgumentValueFromParameterPath extension.bundle.js:2:1766365
getOperationArgumentValueFromParameter extension.bundle.js:2:1765872
WebSiteManagementClient.ServiceClient.sendOperationRequest extension.bundle.js:2:1762311
WebApps.listNext extension.bundle.js:2:553051
SubscriptionTreeItem.<anonymous> extension.bundle.js:2:4651125
fulfilled extension.bundle.js:2:4650147
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by zhangadreedom** [comment] 2022-01-06 06:15
@Ramprasadaddanki could you please provide more information about this issue? like error screenshot, which action you use...

**Comment by joechung-msft** [comment] 2022-02-17 05:44
Duplicate of #332

**Closed by joechung-msft** 2022-02-17 05:44 UTC
