### ISSUE TITLE
Logic App Preview from (Visual Studi)

### ISSUE THREAD

**Issue by amarmanchalagithub** [Azure/logicapps#190] opened 2020-10-29 19:05 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureLogicAppsV2.createCodeless
Error type: Error
Error Message: Failed to get latest templates: Unexpected token E in JSON at position 0

Version: 0.0.4
OS: win32
OS Release: 6.1.7601
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
CentralTemplateProvider.<anonymous> extension.bundle.js:164:430605
fulfilled extension.bundle.js:164:427159
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by joechung-msft** [comment] 2020-10-31 08:56
Duplicate of #189

**Closed by joechung-msft** 2020-10-31 08:56 UTC
Labels: duplicate, preview
