### ISSUE TITLE
VSCode Extension prompts for Language selection, the errors because selection was made

### ISSUE THREAD

**Issue by Jtango18** [Azure/logicapps#697] opened 2022-12-20 05:13 UTC
### Describe the Bug

When using the VSCode extension, right-click Deploy asks if you want to initialise your Project for use with VSCode. 

Selecting 'Yes' prompts selection of a language. 

Upon selecting any language, an error happens with the notification "Internal error: Expected value to be neither null, undefined, nor empty: projectLanguage"

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

1. Open a Logic Apps project in VS Code with Logic Apps Standard Extension installed
2. Right click the project folder and choose "Deploy to Azure"
3. When prompted, chose "yes" for enable this project for VSCode
4. Select a new or existing Logic App to deploy to
5. Choose any language from the drop down

### Screenshots or Videos

![CleanShot 2022-12-20 at 16 08 05](https://user-images.githubusercontent.com/801539/208588845-b96a94fd-9799-4f33-8c68-925363363d18.png)

AB#16642737

**Comment by ccastrotrejo** [comment] 2023-01-17 17:05
Hi @Jtango18, thank you very much for raising this issue. I was able to repro it in the newest version. Will work on fixing it and will be done in the next version. In the meantime, there are two workarounds you can try to make it work it.

1.- Make sure you have the `azureLogicAppsStandard.projectRuntime` setting with the desire language in your `.vscode/settings.json` file, like this one
![Screenshot 2023-01-17 at 10 36 10 AM](https://user-images.githubusercontent.com/102700317/212962225-68d44d8a-cbb4-43a2-9c58-f2337ea30827.png)

2.- Make sure you have the Azure Logic Apps Standard: Project Language setting with the desire language in your vscode workspace settings, like this one

![Screenshot 2023-01-17 at 10 58 55 AM](https://user-images.githubusercontent.com/102700317/212963164-0d647bdd-e60c-4c5f-96f6-05a67094a899.png)

**Comment by Jtango18** [comment] 2023-01-18 00:27
Thanks for the assist and update @ccastrotrejo !

**Comment by ccastrotrejo** [comment] 2023-02-17 23:39
This should be fixed with the newest 1.0.46 version.

**Closed by ccastrotrejo** 2023-02-17 23:39 UTC
Labels: bug

**Comment by MrRosendahl** [comment] 2024-11-07 13:16
@ccastrotrejo I'm facing similar issues when using a workspace and a logic app standard custom code.

I'm trying to create a workflow for a logic apps standard (custom code) using `Azure Logic Apps: Create workflow...`, and it works great when I open the project using `Open folder...`, but since this is a workspace project I want to use `Open workspace from file...`. When I open the workspace file and from there try to create a workflow the same way, and select where my logic apps root folder is (sub folder) `LogicApp` I always get this popup `Initialize project for use with VS Code?` with an error.

Azure Logic Apps (Standard) output:
`FuncCoreTools Binaries: C:\Users\myusername\.azurelogicapps\dependencies\FuncCoreTools
1:41:17 PM: Error: Internal error: Expected value to be neither null, undefined, nor empty: projectRuntime`

FuncCoreTools version: 4.0.6280

Create workflow when opening workspace = error
Create workflow when opening folder = works fine

All these settings are from within the workspace, same settings for User/Workspace/all folders:
Azure Functions: Project Language = `Custom` _its a project logic apps standard custom code_
Azure Functions: Project Language Model = `0` _I have no idea what this zero does, but picks first from an array?_
Azure Logic Apps Standard: Project Language: `Javascript`

![Image](https://github.com/user-attachments/assets/7c0a0b8d-9828-4689-b578-2ef977501b4f)
![Image](https://github.com/user-attachments/assets/b002ab26-2e99-4116-b707-053225e08ccc)
![Image](https://github.com/user-attachments/assets/57235177-0a02-4a36-8f5f-125eb9bc2551)

**Comment by MrRosendahl** [comment] 2024-11-07 13:59
Hi @ccastrotrejo, what I ment was that I that I tried to create a workflow using the `Azure Logic Apps: Create workflow...`, 
in two ways

1. `Open folder...` &rarr; `Azure Logic Apps: Create workflow...` &rarr; `Stateful` &rarr; `TheName` = works, the workflow is created
2. `Open Workspace From File` (wait for loading and select folder containing yout logic app, works) &rarr; `Azure Logic Apps: Create workflow...` &rarr; `Select folder containing yout logic app (again), works?` &rarr; `Popup: Initialize project for use with VS Code` &rarr; `Yes` &rarr; `Internal error`

**Comment by MrRosendahl** [comment] 2024-11-07 15:04
Yes I know about the workspace file and I've already opened that 👍, I did not include that part in my step 2, but yes did open the workspace file. The issue is that I get an error when I try to create a workflow when I have opened the workspace (file).

**Comment by ccastrotrejo** [comment] 2024-11-07 16:48
@MrRosendahl ok, this seems to be an odd behavior. Do you know what is the value of the projectRuntime setting?
![Image](https://github.com/user-attachments/assets/8fcc40c3-97fa-499d-8809-b4deeb3c6993)
