### ISSUE TITLE
Azure Blob Queue Trigger not fired when debugging - invalid reference in connections.json

### ISSUE THREAD

**Issue by sjwaight** [Azure/logicapps#187] opened 2020-10-19 04:14 UTC
I have messages in a Queue (in a Storage account in Australia East) and have configured my Stateful workflow's Azure Storage Queue Connector ("When a specified number of messages are in a given queue") for it (the Connector is pointed at the API in  West US2). Even when the message threshold is met the trigger appears not to be fired (in fact is - see below).

Below is what is in the Terminal in VS Code.

==========

Azure Functions Core Tools (2.7.2936 Commit hash: c00b06616a741dcdf70a3061fc415adde84010f8)
Function Runtime Version: 2.0.14494.0
AZURE_FUNCTIONS_ENVIRONMENT: Development

Functions:

WorkflowDispatcher: workflowRuntimeTrigger

For detailed output, run func with --verbose flag.
Hosting environment: Development
Content root path: C:\Work\ImageNoCodeAIProcessor\bin\Debug\netcoreapp2.2
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.
[2020-10-19T04:00:31.437] Host lock lease acquired by instance ID '000000000000000000000000F76D9C0B'.

=====

The Terminal just sits on the above and does not change no matter how many messages I add.
 
Now...

If I run the the Functions host from the Terminal and provide the --verbose flag I see additional debugging information as follows. I am unable to resolve this issue as the connections.json file is generated by the Logic Apps tooling.

`[2020-10-19T04:09:55.378] Workflow trigger ends. flowName='ImageAIProcessor', triggerName='When_a_specified_number_of_messages_are_in_a_given_queue', flowId='029d97381c6343f2a93755782065eb6a', flowSequenceId='08585985270038687248', status='Failed', statusCode='BadRequest', error='{"code":"BadRequest","message":"The API connection reference 'azurequeues' is not referenced correctly. Make 
sure that all connections used in triggers of type 'ApiConnection' are declared under the 'managedApiConnections' in the connections.json."}', extensionVersion='1.0.0.0', siteName='', slotName='', durationInMilliseconds='253', flowRunSequenceId='', inputsContentSize='129', outputsContentSize='-1', clientTrackingId='08585985262904219640287440771CU00', properties='{"$schema":"2016-06-01","startTime":"2020-10-19T04:09:55.0565651Z","endTime":"2020-10-19T04:09:55.3774055Z","status":"Failed","code":"BadRequest","resource":{"workflowId":"029d97381c6343f2a93755782065eb6a","workflowName":"ImageAIProcessor","runId":"08585985262904219640287440771CU00","triggerName":"When_a_specified_number_of_messages_are_in_a_given_queue"},"correlation":{"clientTrackingId":"08585985262904219640287440771CU00"},"error":{"code":"BadRequest","message":"The API connection reference 'azurequeues' is not referenced correctly. Make sure that all connections used in triggers of type 'ApiConnection' are declared under the 'managedApiConnections' in the connections.json."}}', triggerType='ApiConnection', flowScaleUnit='cu00', triggerKind='', sourceTriggerHistoryName='', failureCause='', activityId='230082c3-c400-42f9-9185-e03862997e55'.`

**Comment by rarayudu** [comment] 2020-10-19 23:18
Hi Sjwaight,

would you be able to share your workflow.json and connections.json files with us?

**Comment by sjwaight** [comment] 2020-10-20 00:13
Happy to share - can I share internally via email?

**Comment by rarayudu** [comment] 2020-10-20 01:40
Sure, please share at "rarayudu@microsoft.com"

**Comment by rarayudu** [comment] 2020-10-20 18:11
We found the issue, will prepare the fix and release it as part of our next release.

**Comment by nidpathak** [comment] 2020-11-02 19:00
@sjwaight We now have the fix for this issue included as part of latest VSCode Marketplace release (the latest extension (version 0.0.5)) and nuget location is here:- https://www.nuget.org/packages/Microsoft.Azure.Workflows.WebJobs.Extension/1.0.0.8-preview.

Please feel free to give it a try and let us know if the issue is resolved.

**Comment by rarayudu** [comment] 2020-11-03 18:32
This should be fixed now with recent release.

**Closed by rarayudu** 2020-11-03 18:32 UTC
Labels: preview
